name: manajemen_keuangan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/times.ttf
        - asset: assets/fonts/timesbd.ttf
          weight: 700
        - asset: assets/fonts/timesbi.ttf
          style: italic
        - asset: assets/fonts/timesi.ttf
          style: italic
